### ISSUE TITLE
Prison Padoru

### ISSUE THREAD

**Issue by JoaoCostaIFG** [Diogogrosario/Logic-Programming#1]
<.<

**Comment by rfontao** [comment]
I agree

**Comment by Educorreia932** [comment]
https://cdn.discordapp.com/attachments/679277916768567303/812076696517476372/prison_padoru.png

**Comment by JoaoCostaIFG** [comment]
Why the force push, m8?

**Comment by Educorreia932** [comment]
卐

Ṇ̦̠͖í͖g̢̬g̪͍͖e̺͉̭͎͍̘͜r̢͓̼̱̺ṣ̪ͅ
--


👨🏿

**Comment by Diogogrosario** [comment]
Will be fixed in release 1.1
